services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    command: redis-server
    networks:
      - redis-net

  redis-r1:
    image: redis
    ports:
      - "6380:6379"
    command: redis-server --replicaof redis 6379
    depends_on:
      - redis
    networks:
      - redis-net

networks:
  redis-net:
    driver: bridge
