services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./conf:/etc/redis/conf
    command: redis-server /etc/redis/conf/redis.conf
    networks:
      - redis-net

  redis-r1:
    image: redis
    ports:
      - "6380:6379"
    volumes:
      - ./conf:/etc/redis/conf
    command: redis-server /etc/redis/conf/repl.conf --masterauth $ADMIN_PWD
    depends_on:
      - redis
    networks:
      - redis-net

networks:
  redis-net:
    driver: bridge
